### ISSUE TITLE
Pagina Podcast - Non si caricano le copertine

### ISSUE THREAD

**Issue by Magnetarman** [valeriogalano/pensieriincodice-website#12]
<img width="540" alt="Copertine" src="https://github.com/valeriogalano/pensieriincodice-website/assets/40738529/d1269272-2e42-484b-8be3-2ead2dee6f25">

Non si caricano le copertine dei diversi episodi all'interno della **pagina podcast** come si vede nello screen. Da quanto vedo nell'ispector va proprio in errore 404, come nel secondo screen qui sotto.

<img width="422" alt="Immagine2" src="https://github.com/valeriogalano/pensieriincodice-website/assets/40738529/76b7cc38-b668-4f87-a87a-32727525c075">

**Comment by progressify** [comment]
A quanto pare le immagini sono proprio rotte ovunque.
Sia qui (dove hai segnalato tu): https://pensieriincodice.it/episodes/
E sia qui: https://pensieriincodice.it/episodes/123/

Provo a risolvere

**Comment by Magnetarman** [comment]
Ti confermo, che va in 404 anche nelle singole pagine della puntata. Provato con vari browser, con vari modi. Forse si deve assestare il sito ?!?

**Comment by Magnetarman** [comment]
![image](https://github.com/valeriogalano/pensieriincodice-website/assets/40738529/51ad10bb-109d-43ac-84f1-10e010b5eb4d)

E Da quel che noto anche il logo nella repo non carica andando in 404. Forse è saltato qualcosa ?

**Comment by valeriogalano** [comment]
Risolto con commit [1c753e0ce28fdfbd9341b8c432e06c76f7c8c78a](https://github.com/valeriogalano/pensieriincodice-website/commit/1c753e0ce28fdfbd9341b8c432e06c76f7c8c78a)

**Comment by valeriogalano** [comment]
Chiudo
