### ISSUE TITLE
Icone mancanti in Storia del podcast

### ISSUE THREAD

**Issue by valeriogalano** [valeriogalano/pensieriincodice-website#7]
Nella sezione Storia del podcast non compaiono le icone a fianco ai titoli

![image](https://github.com/valeriogalano/pensieriincodice-website/assets/342634/3130cf2a-36c3-4b68-8dc7-ef10a3826f59)

**Comment by progressify** [comment]
è collegata a questa https://github.com/valeriogalano/pensieriincodice-website/issues/4
ti faccio un unica pr che risolve entrambi i problemi

**Comment by progressify** [comment]
![image](https://github.com/valeriogalano/pensieriincodice-website/assets/11472632/6f721058-2baf-4f11-83ff-b6efc4421c98)

eccole

**Comment by valeriogalano** [comment]
Risolto. Grazie @progressify
