### ISSUE TITLE
Immagini non visibili su Antennapod 

### ISSUE THREAD

**Issue by progressify** [valeriogalano/pensieriincodice-website#9]
Con questo feed:

https://valeriogalano.github.io/pensieriincodice-website/podcast/index.xml

In Antennapod non visualizzo le immagini del podcast
![Screenshot_20231206-092859](https://github.com/valeriogalano/pensieriincodice-website/assets/11472632/3ef32637-2d64-41b3-8081-ac23882a2d8b)

**Comment by valeriogalano** [comment]
Risolto
